"""add_retreatment_count_to_usage_stats

Revision ID: 325c438afb0b
Revises: 1e478d725a3c
Create Date: 2025-08-01 01:58:01.770068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325c438afb0b'
down_revision: Union[str, Sequence[str], None] = '1e478d725a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_stats', sa.Column('retreatment_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_stats', 'retreatment_count')
    # ### end Alembic commands ###
