[phases.setup]
nixPkgs = ["git", "gcc", "python310"]

[phases.install]
cmds = [
    "chmod +x buildpack.sh",
    "./buildpack.sh",
    "python -m ensurepip --upgrade",
    "python -m pip install -r requirements.txt",
    "chmod +x postinstall.sh",
    "./postinstall.sh"
]

[start]
cmd = "chmod +x verify_and_start.sh && ./verify_and_start.sh" 