[phases.setup]
nixPkgs = ["git", "build-essential", "python3-dev", "libgl1-mesa-glx", "python3-distutils", "libglib2.0-0", "libsm6", "libxext6", "libxrender1", "libgomp1", "tesseract-ocr", "libtesseract-dev"]

[phases.install]
cmds = [
    "chmod +x buildpack.sh",
    "./buildpack.sh",
    "pip install -r requirements.txt",
    "pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1",
    "pip install git+https://github.com/facebookresearch/detectron2.git@b15f64ec4429e23a148972175a0207c5a9ab84cf"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT" 