[phases.setup]
nixPkgs = ["git", "gcc", "python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
    "chmod +x buildpack.sh",
    "./buildpack.sh",
    "pip install -r requirements.txt",
    "chmod +x postinstall.sh",
    "./postinstall.sh"
]

[start]
cmd = "chmod +x verify_and_start.sh && ./verify_and_start.sh" 