[phases.setup]
nixPkgs = ["git", "gcc", "python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
    "chmod +x buildpack.sh",
    "./buildpack.sh",
    "pip install --break-system-packages torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1",
    "pip install --break-system-packages detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/index.html",
    "pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "chmod +x verify_and_start.sh && ./verify_and_start.sh" 