[phases.setup]
nixPkgs = ["git", "gcc", "python310", "python310Packages.pip", "python310Packages.setuptools", "conda"]

[phases.install]
cmds = [
    "chmod +x buildpack.sh",
    "./buildpack.sh",
    "pip install --break-system-packages -r requirements-torch.txt",
    "pip install --break-system-packages -r requirements.txt",
    "conda install -c conda-forge detectron2 -y"
]

[start]
cmd = "chmod +x verify_and_start.sh && ./verify_and_start.sh" 